image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
    - test

workflow:
    rules:
        - if: $CI_MERGE_REQUEST_ID             # Execute jobs in merge request context
        - if: $CI_COMMIT_BRANCH == 'main'      # Execute jobs when a new commit is pushed to main branch

test:
    stage: test
    script:
        - "dotnet test --configuration=Release"